language: c

dist: trusty
sudo: required

branches:
  only:
    - dh_builds

env:
  global:
    secure: "Rn24NHlrS5q70A5bIIvKjvB5AJ9HwnwZraRXvTZLs+XPbXblWorTRTS5aKq4VLoqRZp9a+TU6zyy1MTbwbi7OOGFMVHsqa1MMrESPmEYjPdgAlFmz8iyzh03eF5xNEFu0fAZgCQykVWl3YCOjcKcoe1tDiOztNTdAr3WKoEYPdg+NGug0RP87EJyNDu8UE0RdL6B8OVmSecIdcXJ0w8jxbCYRwYBCPuWjuJ0uKZwVRTqdAsn/6oVSmOcrJ0yi7kjPslOLNLjCooUyCjduTFGS7UWPBib7Ww7WTxIC3qSdZ/CmflbRuzV2rHC54dgqWAM5+v1sU4uUtkH0XFZmTSAV5KIwgoVOshjIZfI4OvFAuD/n3v0KkNt6ikdsRE2HO9dovys8kOTQIeZVtyH78cpmOyByFhebY9Uej+B5pZBlt2iqWoqtCBI3gQe/5M5Z08NwrycwZvti+BsmINgNcnyf4HzGRvV1NmCvv+nlMJydZCS84sp8EhpRkw1D7MP9DOP/4VUHw3YcjrbJ/cpkan1/jmckxOdwLADE8w9xNJb48QwYoz6e1GzB8KlZj3hpz+Hc4T6DMldeJXLZ4XjgEmLQGRIrHSGX9uLPClyrhkJbu2C0mgfjNi45jLfcKKoxEKbbPqw2fWDLQItbltTjdWljDPNWqFKBkU5g0zDbskxazY="


rvm:
  - 2.5

install:
  - sudo add-apt-repository ppa:linuxsimba/libvirt-udp-tunnel -y
  - sudo apt-get update
  - sudo apt-get install libvirt-bin libvirt-dev qemu-utils qemu -y
  - sudo /etc/init.d/libvirt-bin restart
  - sudo virsh pool-define-as --name default --type dir --target /var/lib/libvirt/images
  - sudo virsh pool-autostart default || true
  - sudo virsh pool-build default || true
  - sudo virsh pool-start default || true
  - sudo /etc/init.d/libvirt-bin restart
  - sudo libvirtd --version
  - wget https://releases.hashicorp.com/vagrant/2.1.2/vagrant_2.1.2_x86_64.deb
  - sudo dpkg -i vagrant_2.1.2_x86_64.deb
  - vagrant plugin install vagrant-libvirt
  - curl -L -o packer.zip https://releases.hashicorp.com/packer/1.2.4/packer_1.2.4_linux_amd64.zip && unzip -d bin packer.zip

script:
  - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - PACKER_LOG=1 ./bin/packer build -only=qemu -var headless=true -var compression_level=9 freebsd-11.1-amd64.json
  - kill %1
